
in_image: '/scratch/jdekrake/synth_hippo/Mixed_generated/image_{subjid}.nii.gz'
in_label: '/scratch/jdekrake/synth_hippo/Mixed_generated/labels_{subjid}.nii.gz'

out_resolution: '128x256x128'

task: Task102_synsegGenDetailed #must be Task###_name where ### is >= 100
trainer: nnUNetTrainerV2
architecture: 3d_fullres
checkpoint: model_best

nnunet_env:
  nnUNet_raw_data_base: 'raw_data'
  nnUNet_preprocessed: 'preprocessed'
  RESULTS_FOLDER: 'trained_models'

nnunet_env_tmp:
  nnUNet_raw_data_base: 'raw_data'
  nnUNet_preprocessed: '$SLURM_TMPDIR/preprocessed'
  RESULTS_FOLDER: 'trained_models'

