
in_image:
 - '/scratch/jdekrake/Hippocampal_AutoTop_tests/trainingdata_HCP1200_modalities-all_v4reg/{subjid}_hemi-{hemi}_T1w.nii.gz'
 - '/scratch/jdekrake/Hippocampal_AutoTop_tests/trainingdata_HCP1200_modalities-all_v4reg/{subjid}_hemi-{hemi}_T2w.nii.gz'
 - '/scratch/jdekrake/Hippocampal_AutoTop_tests/trainingdata_HCP1200_modalities-all_v4reg/{subjid}_hemi-{hemi}_b1000.nii.gz'
in_label: '/scratch/jdekrake/Hippocampal_AutoTop_tests/trainingdata_HCP1200_modalities-all_v4reg/{subjid}_hemi-{hemi}_lbl.nii.gz'

trainin_sub_list: 'training.txt' #for using a predetermined train/test split

modalities:
 - 'T1w'
 - 'T2w'
 - 'b1000'

out_resolution: '128x256x128'

task: Task105_hcp1200_trimodal #must be Task###_name where ### is >= 100
trainer: nnUNetTrainerV2
architecture: 3d_fullres
checkpoint: model_best

nnunet_env:
  nnUNet_raw_data_base: 'raw_data'
  nnUNet_preprocessed: 'preprocessed'
  RESULTS_FOLDER: 'trained_models'

nnunet_env_tmp:
  nnUNet_raw_data_base: 'raw_data'
  nnUNet_preprocessed: '$TMPDIR/preprocessed'
  RESULTS_FOLDER: 'trained_models'
